#pragma once

#include <array>
#include <cstdint>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

namespace smr_machine {

enum class CommandType : std::uint8_t {
  Submit = 1,
  Cancel = 2,
  Fill = 3,
  Fail = 4,
  Modify = 5,
};

enum class SideCode : std::uint8_t {
  Buy = 1,
  Sell = 2,
};

struct CommandEvent {
  std::uint64_t ts_ns;
  CommandType type;
  SideCode side;
  std::int32_t qty;
  std::int32_t px;
  std::array<char, 24> id;
  std::array<char, 24> trader;
  std::array<char, 64> reason;
};

static_assert(std::is_trivially_copyable_v<CommandEvent>, "CommandEvent must be trivially copyable");

inline std::array<char, 24> pack_short(std::string_view value) {
  if (value.size() >= 24) {
    throw std::invalid_argument("field exceeds 23 bytes");
  }
  std::array<char, 24> out{};
  for (std::size_t i = 0; i < value.size(); ++i) {
    out[i] = value[i];
  }
  return out;
}

inline std::array<char, 64> pack_reason(std::string_view value) {
  if (value.size() >= 64) {
    throw std::invalid_argument("reason exceeds 63 bytes");
  }
  std::array<char, 64> out{};
  for (std::size_t i = 0; i < value.size(); ++i) {
    out[i] = value[i];
  }
  return out;
}

inline std::string unpack_cstr(const auto& buffer) {
  std::size_t size = 0;
  while (size < buffer.size() && buffer[size] != '\0') {
    ++size;
  }
  return std::string(buffer.data(), size);
}

inline std::string to_script_line(const CommandEvent& event) {
  std::ostringstream out;
  switch (event.type) {
    case CommandType::Submit:
      out << "SUBMIT " << event.ts_ns << ' ' << unpack_cstr(event.id) << ' '
          << unpack_cstr(event.trader) << ' '
          << (event.side == SideCode::Buy ? "BUY" : "SELL") << ' ' << event.qty << ' '
          << event.px;
      return out.str();
    case CommandType::Cancel:
      out << "CANCEL " << event.ts_ns << ' ' << unpack_cstr(event.id);
      return out.str();
    case CommandType::Fill:
      out << "FILL " << event.ts_ns << ' ' << unpack_cstr(event.id) << ' ' << event.qty << ' '
          << event.px;
      return out.str();
    case CommandType::Fail:
      out << "FAIL " << event.ts_ns << ' ' << unpack_cstr(event.reason);
      return out.str();
    case CommandType::Modify:
      out << "MODIFY " << event.ts_ns << ' ' << unpack_cstr(event.id) << ' ' << event.qty << ' '
          << event.px;
      return out.str();
  }
  throw std::logic_error("unsupported command type");
}

inline void write_script_file(const std::string& path, const std::vector<CommandEvent>& events) {
  std::ofstream out(path);
  if (!out) {
    throw std::runtime_error("failed to open output path: " + path);
  }
  out << "# generated by cpp/src/generate_scenario.cpp\n";
  for (const auto& event : events) {
    out << to_script_line(event) << '\n';
  }
}

inline CommandEvent make_submit(
    std::uint64_t ts_ns, std::string_view id, std::string_view trader, SideCode side, std::int32_t qty,
    std::int32_t px) {
  return CommandEvent{
      .ts_ns = ts_ns,
      .type = CommandType::Submit,
      .side = side,
      .qty = qty,
      .px = px,
      .id = pack_short(id),
      .trader = pack_short(trader),
      .reason = {},
  };
}

inline CommandEvent make_cancel(std::uint64_t ts_ns, std::string_view id) {
  return CommandEvent{
      .ts_ns = ts_ns,
      .type = CommandType::Cancel,
      .side = SideCode::Buy,
      .qty = 0,
      .px = 0,
      .id = pack_short(id),
      .trader = {},
      .reason = {},
  };
}

inline CommandEvent make_fill(std::uint64_t ts_ns, std::string_view id, std::int32_t qty, std::int32_t px) {
  return CommandEvent{
      .ts_ns = ts_ns,
      .type = CommandType::Fill,
      .side = SideCode::Buy,
      .qty = qty,
      .px = px,
      .id = pack_short(id),
      .trader = {},
      .reason = {},
  };
}

inline CommandEvent make_fail(std::uint64_t ts_ns, std::string_view reason) {
  return CommandEvent{
      .ts_ns = ts_ns,
      .type = CommandType::Fail,
      .side = SideCode::Buy,
      .qty = 0,
      .px = 0,
      .id = {},
      .trader = {},
      .reason = pack_reason(reason),
  };
}

inline CommandEvent make_modify(std::uint64_t ts_ns, std::string_view id, std::int32_t qty, std::int32_t px) {
  return CommandEvent{
      .ts_ns = ts_ns,
      .type = CommandType::Modify,
      .side = SideCode::Buy,
      .qty = qty,
      .px = px,
      .id = pack_short(id),
      .trader = {},
      .reason = {},
  };
}

}  // namespace smr_machine
